"""add_unique_constraint_steam_profile_file

Revision ID: 7a092709dc7b
Revises: 558d2f005730
Create Date: 2026-03-31 13:42:01.109894

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "7a092709dc7b"
down_revision: Union[str, Sequence[str], None] = "558d2f005730"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "uq_runs_steam_profile_file",
        "runs",
        ["steam_id_hash", "profile", "file_name"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_runs_steam_profile_file", table_name="runs")
    # ### end Alembic commands ###
